apiVersion: v1
kind: Service
metadata:
  labels:
    name: webshop
  name: webshop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: webshop
  type: LoadBalancer

                  