apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
    version: green  
  name: customer-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer
    version: green  
