apiVersion: v1
kind: Service
metadata:
  labels:
    name: customer-green
  name: customer-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer-green
