apiVersion: v1
kind: Service
metadata:
  labels:
    app: webshop
    version: green    
  name: webshop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webshop
    version: green        
  type: LoadBalancer

                  