apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
    version: blue
  name: order-blue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: order
    version: blue
