apiVersion: v1
kind: Service
metadata:
  labels:
    name: catalog
    tier: microservice  
  name: catalog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog
