apiVersion: v1
kind: Service
metadata:
  labels:
    name: catalog
  name: catalog
  tier: microservice  
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog
