apiVersion: v1
kind: Service
metadata:
  labels:
    name: customer
    tier: microservice    
  name: customer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer
