apiVersion: v1
kind: Service
metadata:
  labels:
    name: order
    tier: microservice    
  name: order
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web    
  selector:
    app: order
