apiVersion: v1
kind: Service
metadata:
  labels:
    name: webshop
  name: webshop
  tier: microservice    
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webshop
  type: LoadBalancer

                  