# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.0.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-25T14:06:06Z"
  labels:
    app: customer
  name: customer
spec:
  containers:
  - image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/shop/customer:1.0.0
    name: customer
    securityContext: {}
    resources:
      requests:
        cpu: "25m"
        memory: "96Mi"
      limits:
        cpu: "50m"
        memory: "192Mi"       

